# Generated by Django 5.0.6 on 2024-06-11 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGen', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idPat', models.AutoField(primary_key=True, serialize=False)),
                ('lastnPat', models.CharField(max_length=150)),
                ('namePat', models.CharField(max_length=150)),
                ('pldatePat', models.TextField()),
                ('birthPat', models.DateField()),
                ('fagePat', models.CharField(max_length=150)),
                ('natiPat', models.CharField(max_length=150)),
                ('placePat', models.TextField(max_length=150)),
                ('ciPat', models.CharField(max_length=10)),
                ('genPat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Historiales.gender')),
            ],
        ),
    ]
