# Generated by Django 5.0.6 on 2024-06-11 04:41

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='creation',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
