# Generated by Django 5.0.6 on 2024-06-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0002_patient_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='creation',
        ),
    ]
