# Generated by Django 5.0.6 on 2024-06-11 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0004_patient_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='creation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
