# Generated by Django 5.0.6 on 2024-06-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0006_contactcita_madrecita_padrecita_patient_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='num',
        ),
        migrations.AddField(
            model_name='madrecita',
            name='cell',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='madrecita',
            name='tf_casa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='madrecita',
            name='tf_tra',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='ContactCita',
        ),
    ]
