# Generated by Django 5.0.6 on 2024-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0008_remove_madrecita_cell_remove_madrecita_tf_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='seguroPat',
            field=models.BooleanField(default=False),
        ),
    ]
