# Generated by Django 5.0.6 on 2024-07-17 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0009_patient_seguropat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField(default=datetime.date.today)),
                ('nombreAlergia', models.CharField(max_length=150)),
            ],
        ),
    ]
