# Generated by Django 5.0.6 on 2024-07-18 03:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0011_pataler'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField(default=datetime.date.today)),
                ('prenatal', models.TextField()),
                ('natal', models.TextField()),
                ('app', models.TextField()),
                ('apf', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiales.patient')),
            ],
        ),
    ]
