# Generated by Django 5.0.6 on 2024-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0013_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod3', models.CharField(max_length=10)),
                ('nombrecie', models.CharField(max_length=250)),
            ],
        ),
    ]
