# Generated by Django 5.0.7 on 2024-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0014_cie10'),
    ]

    operations = [
        migrations.AddField(
            model_name='madrecita',
            name='dir_mom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madrecita',
            name='ruc_mom',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='madrecita',
            name='telf_mom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='padrecita',
            name='dir_fat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrecita',
            name='ruc_fat',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='padrecita',
            name='telf_fat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
