# Generated by Django 5.0.6 on 2024-07-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0015_madrecita_dir_mom_madrecita_ruc_mom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombregen_med', models.CharField(max_length=150)),
                ('nombrecom_med', models.CharField(max_length=150)),
                ('tipo_med', models.CharField(max_length=150)),
            ],
        ),
    ]
