# Generated by Django 5.0.6 on 2024-07-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0016_medicina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergia',
            name='nombreAlergia',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
