# Generated by Django 5.0.6 on 2024-07-21 23:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0017_alter_alergia_nombrealergia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField(default=datetime.date.today)),
                ('tratamiento', models.BooleanField(default=False)),
                ('cie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Historiales.cie10')),
                ('obs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Historiales.observaciones')),
            ],
        ),
    ]
