# Generated by Django 5.0.6 on 2024-07-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0018_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='cie',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='cies',
            field=models.ManyToManyField(to='Historiales.cie10'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='tratamiento',
            field=models.CharField(choices=[('Agudo', 'Agudo'), ('Crónico', 'Crónico')], max_length=50),
        ),
    ]
