# Generated by Django 5.0.7 on 2024-07-22 16:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0019_remove_diagnostico_cie_diagnostico_cies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='obs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Historiales.observaciones', unique=True),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField(default=datetime.date.today)),
                ('alimentacion', models.CharField(max_length=150)),
                ('examen', models.CharField(max_length=150)),
                ('total', models.IntegerField()),
                ('cantidad', models.CharField(max_length=150)),
                ('via', models.CharField(max_length=150)),
                ('frecuencia', models.CharField(max_length=150)),
                ('duracion', models.CharField(max_length=150)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Historiales.medicina')),
                ('obsmed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiales.observaciones')),
            ],
        ),
    ]
