# Generated by Django 5.0.7 on 2024-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0020_alter_diagnostico_obs_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='alimentacion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='examen',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='alimentacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='examen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
