# Generated by Django 5.0.6 on 2024-07-26 01:36

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0021_remove_receta_alimentacion_remove_receta_examen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curvas',
            fields=[
                ('idcur', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField(default=datetime.date.today)),
                ('estatura_mom', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estatura_dad', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('age_pat', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estatura_pat', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('IMC', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiales.patient')),
            ],
        ),
    ]
