# Generated by Django 5.0.6 on 2024-07-26 02:35

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0023_curvas_per_enc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstaturasRep',
            fields=[
                ('idest', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField(default=datetime.date.today)),
                ('estatura_mom', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estatura_dad', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.RemoveField(
            model_name='curvas',
            name='estatura_dad',
        ),
        migrations.RemoveField(
            model_name='curvas',
            name='estatura_mom',
        ),
    ]
