# Generated by Django 5.0.6 on 2024-07-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0024_estaturasrep_remove_curvas_estatura_dad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estaturasrep',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Historiales.patient'),
        ),
    ]
