# Generated by Django 5.0.6 on 2024-07-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0025_estaturasrep_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaturasrep',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Historiales.patient'),
        ),
    ]
