# Generated by Django 5.0.6 on 2024-08-01 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0027_alter_curvas_age_pat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='obs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Historiales.observaciones'),
        ),
    ]
