# Generated by Django 5.0.6 on 2024-08-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0028_alter_diagnostico_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='prox_ci',
            field=models.DateField(blank=True, null=True),
        ),
    ]
