# Generated by Django 4.2.7 on 2024-04-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0002_nombredia_alter_citadia_id_citadia_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('horaFInal', models.TimeField()),
                ('estado', models.BooleanField(default=False)),
                ('diaH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Citas.citadia')),
            ],
        ),
    ]
