# Generated by Django 4.2.7 on 2024-05-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0004_horasdia_remove_diahorario_horafinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diahorario',
            name='diaH',
        ),
        migrations.DeleteModel(
            name='CitaDia',
        ),
        migrations.DeleteModel(
            name='NombreDia',
        ),
    ]
