# Generated by Django 4.2.7 on 2024-05-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0005_remove_diahorario_diah_delete_citadia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diahorario',
            name='diaH',
            field=models.DateField(blank=True, null=True),
        ),
    ]
