# Generated by Django 5.0.6 on 2024-05-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0006_diahorario_diah'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_us', models.CharField(max_length=150)),
                ('apellido_us', models.CharField(max_length=150)),
                ('correo_us', models.CharField(max_length=150)),
                ('telf_us', models.CharField(max_length=10)),
            ],
        ),
    ]
