# Generated by Django 5.0.6 on 2024-05-28 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0007_usuariocli'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerosCli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gen', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='usuariocli',
            name='gen_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Citas.generoscli'),
        ),
    ]
