# Generated by Django 4.2.7 on 2024-05-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0009_usuariocli_is_active_usuariocli_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocli',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuariocli',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuariocli',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuariocli',
            name='password',
        ),
        migrations.AddField(
            model_name='usuariocli',
            name='pass_us',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuariocli',
            name='correo_us',
            field=models.CharField(max_length=150),
        ),
    ]
