# Generated by Django 5.0.6 on 2024-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0011_alter_usuariocli_telf_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocli',
            name='pass_us',
            field=models.CharField(max_length=300),
        ),
    ]
