# Generated by Django 5.0.6 on 2024-06-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0012_alter_usuariocli_pass_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rep', models.CharField(max_length=150)),
                ('apellido_rep', models.CharField(max_length=150)),
                ('correo_rep', models.CharField(max_length=150)),
                ('telf_rep', models.CharField(max_length=10)),
            ],
        ),
    ]
