# Generated by Django 5.0.6 on 2024-06-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0013_representante'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentanteCita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rep', models.CharField(max_length=150)),
                ('apellido_rep', models.CharField(max_length=150)),
                ('correo_rep', models.CharField(max_length=150)),
                ('telf_rep', models.CharField(max_length=10)),
                ('date_rep', models.DateField()),
                ('time_rep', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
