# Generated by Django 5.0.6 on 2024-06-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0015_citasol_contactcita_madrecita_padrecita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasol',
            name='cort_da',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citasol',
            name='nom_da',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
