# Generated by Django 5.0.6 on 2024-06-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0016_citasol_cort_da_citasol_nom_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasol',
            name='est_da',
            field=models.BooleanField(default=False),
        ),
    ]
