# Generated by Django 5.0.6 on 2024-06-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0017_citasol_est_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasol',
            name='telf_da',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
