# Generated by Django 5.0.6 on 2024-06-09 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0019_factcitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcitas',
            name='fechfac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Citas.citasol'),
        ),
    ]
