# Generated by Django 5.0.6 on 2024-06-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0020_alter_factcitas_fechfac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocli',
            old_name='apellido_us',
            new_name='correo_cli',
        ),
        migrations.RenameField(
            model_name='usuariocli',
            old_name='correo_us',
            new_name='nombre_cli',
        ),
        migrations.RenameField(
            model_name='usuariocli',
            old_name='pass_us',
            new_name='pass_cli',
        ),
        migrations.RemoveField(
            model_name='usuariocli',
            name='gen_us',
        ),
        migrations.RemoveField(
            model_name='usuariocli',
            name='nombre_us',
        ),
        migrations.RemoveField(
            model_name='usuariocli',
            name='telf_us',
        ),
    ]
