# Generated by Django 5.0.6 on 2024-06-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0021_rename_apellido_us_usuariocli_correo_cli_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerosCli',
        ),
    ]
