# Generated by Django 5.0.6 on 2024-06-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0022_delete_generoscli'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactCita',
        ),
        migrations.DeleteModel(
            name='MadreCita',
        ),
        migrations.DeleteModel(
            name='PadreCita',
        ),
    ]
