# Generated by Django 5.0.6 on 2024-07-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0023_delete_contactcita_delete_madrecita_delete_padrecita'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasol',
            name='notificacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
