# Generated by Django 5.0.6 on 2024-07-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0024_citasol_notificacion_enviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasol',
            name='correo_da',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
