# Generated by Django 5.0.6 on 2024-08-01 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0025_citasol_correo_da'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolCli',
            fields=[
                ('idCi', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField(default=datetime.date.today)),
                ('nom_da', models.CharField(max_length=150)),
                ('telf_da', models.CharField(max_length=10)),
                ('correo_da', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diahorario',
            name='horario',
        ),
        migrations.DeleteModel(
            name='UsuarioCli',
        ),
        migrations.AddField(
            model_name='citasol',
            name='creation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='factcitas',
            name='creation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='DiaHorario',
        ),
        migrations.DeleteModel(
            name='HorasDia',
        ),
    ]
