# Generated by Django 5.0.6 on 2024-08-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0026_solcli_remove_diahorario_horario_delete_usuariocli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solcli',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
