# Generated by Django 5.0.6 on 2024-08-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0027_solcli_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solcli',
            name='fech_da',
            field=models.DateField(blank=True, null=True),
        ),
    ]
