# Generated by Django 5.0.6 on 2024-08-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0028_solcli_fech_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='solcli',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
    ]
