# Generated by Django 5.0.6 on 2024-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0031_citasol_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasol',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factcitas',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
