# Generated by Django 5.0.6 on 2024-08-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0033_factcitas_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcitas',
            name='comentario',
        ),
    ]
