# Generated by Django 5.0.6 on 2024-08-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0034_remove_factcitas_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factcitas',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
